"""
Universe / security-master layer.

The permanent, authoritative creator of security identities. Coverage sources are
declared in manifests/registry.csv; for each, a manifest lists the securities,
and this layer creates the sec.security identity + TICKER identifier and sets CIK
when resolvable. OpenFIGI then enriches identities with FIGIs; EDGAR / bars /
corporate actions resolve an existing identity and skip if it is absent. (See
DEC-017, recorded in chunk 2 alongside the EDGAR resolve-and-skip change.)

Architecture:
    Universe engine (writer / cik / cli)
        ^ consumes CoverageEntry
    Coverage manifests (data)  <- registry.csv declares the open set
        ^ optionally generated by
    build_manifest.py (a generic holdings-CSV -> manifest data generator)

Adding a coverage set (Russell 1000, NASDAQ-100, international, ...) is a registry
row + a manifest; no engine code changes. The engine knows nothing about which
index produced any manifest.

Onboarding contract — how a security enters the system:
    coverage manifest -> universe layer creates identity (+ CIK)
                      -> OpenFIGI enriches with FIGI
                      -> connectors attach fundamentals / bars / actions (resolve-and-skip)

Coverage is operational config (manifests/), not a DEC: the S&P 500 list is a
large-cap US equity SEED universe derived from SPY holdings — explicitly NOT
authoritative S&P 500 membership (that is PIT membership, a separate later item).
"""