"""
Coverage loading.

Coverage sources are declared in registry.csv (name, file, default_type). This
module reads the registry, loads each manifest generically, and returns the
combined, de-duplicated CoverageEntry list plus a per-source report. The manifest
format IS the pluggable seam: adding a coverage set means adding a registry row +
a manifest (optionally generated by build_manifest.py) — no code change here.

Repo path: src/trading_os/universe/coverage.py
"""
from __future__ import annotations

import csv
from pathlib import Path

from .models import CoverageEntry, CoverageSource, SourceLoad


def load_registry(config) -> list[CoverageSource]:
    """Read registry.csv into CoverageSource rows. Missing registry -> []."""
    if not config.registry_path.exists():
        return []
    out: list[CoverageSource] = []
    with config.registry_path.open(newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            name = (row.get("name") or "").strip()
            file = (row.get("file") or "").strip()
            if not name or not file:
                continue
            default_type = (row.get("default_type") or "EQUITY").strip().upper()
            out.append(CoverageSource(
                name=name,
                path=config.manifest_dir / file,
                default_type=default_type,
            ))
    return out


def load_manifest(path: Path, default_type: str | None = None) -> list[CoverageEntry]:
    """
    Read one manifest CSV. Required column: 'ticker'. Optional: 'security_type'
    (falls back to default_type, then 'EQUITY') and 'name'. Missing file -> [].
    Generic: knows nothing about which index produced the file.
    """
    if not path.exists():
        return []
    out: list[CoverageEntry] = []
    with path.open(newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            ticker = (row.get("ticker") or "").strip().upper()
            if not ticker:
                continue
            stype = (row.get("security_type") or default_type or "EQUITY").strip().upper()
            name = (row.get("name") or "").strip() or None
            out.append(CoverageEntry(ticker=ticker, security_type=stype, name=name))
    return out


def load_coverage(config) -> tuple[list[CoverageEntry], list[SourceLoad]]:
    """
    Combine every registered coverage source into one de-duplicated list,
    de-duping by ticker across sources (first registry occurrence wins). Returns
    (entries, per_source_reports). Order follows the registry.
    """
    seen: set[str] = set()
    entries: list[CoverageEntry] = []
    reports: list[SourceLoad] = []
    for src in load_registry(config):
        added = 0
        for e in load_manifest(src.path, src.default_type):
            if e.ticker in seen:
                continue
            seen.add(e.ticker)
            entries.append(e)
            added += 1
        reports.append(SourceLoad(name=src.name, present=src.path.exists(), count=added))
    return entries, reports